name: For GH Pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: dev step
        env:
          var: "develop"
        run: |
          echo env.dev_var
      - name: prod step
        env:
          var: "production"
        run: |
          echo env.var
